@baseUrl=http://localhost:3000/api
@token={{$dotenv TOKEN}}

###
GET {{baseUrl}} HTTP/1.1


###
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "user{{$randomInt 1 10}}@example.com",
    "password": "Test12345!"
}

###
POST {{baseUrl}}/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "user{{$randomInt 1 10}}@example.com",
    "password": "Test12345!"
}

###
GET {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "email": "user{{$randomInt 1 10}}@example.com",
    "password": "Test12345!"
}

###
GET {{baseUrl}}/users/1/columns HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1/columns/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/users/1/columns HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "position": {{$randomInt 1 100}},
    "title": "Title {{$randomInt 1 100}}"
}

###
PATCH {{baseUrl}}/users/1/columns/{{$randomInt 1 100}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Title {{$guid}}"
}

###
DELETE {{baseUrl}}/users/1/columns/{{$randomInt 1 100}} HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1/columns/1/cards HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1/columns/1/cards/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/users/1/columns/1/cards HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Card #{{$randomInt 1 100}}",
    "description": "Description {{$guid}}"
}

###
PATCH {{baseUrl}}/users/1/columns/1/cards/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "Description {{$guid}}"
}

###
DELETE {{baseUrl}}/users/1/columns/1/cards/3 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1/columns/1/cards/1/comments HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/users/1/columns/1/cards/1/comments/1 HTTP/1.1
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/users/1/columns/1/cards/1/comments HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "Comment {{$guid}}"
}

###
PATCH  {{baseUrl}}/users/1/columns/1/cards/1/comments/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "Comment {{$guid}}"
}

###
DELETE {{baseUrl}}/users/1/columns/1/cards/1/comments/{{$randomInt 1 100}} HTTP/1.1
Authorization: Bearer {{token}}
